[workspace]
members = [".", "xtask"]
exclude = ["bootloader"]

[package]
name = "pager"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_arch = "arm")'.dependencies]
embassy-executor = { version = "0.10.0", features = ["platform-cortex-m", "executor-thread", "defmt"] }
embassy-nrf = { version = "0.11.0", features = ["defmt", "nrf52840", "time-driver-rtc1", "gpiote", "unstable-pac", "rt"] }
embassy-time = { version = "0.5.1", features = ["defmt", "defmt-timestamp-uptime"] }
cortex-m = { version = "0.7.7", features = ["inline-asm"] }
cortex-m-rt = "0.7.3"
defmt = "1.0"
defmt-rtt = "1.0"
panic-probe = { version = "1.0", features = ["print-defmt"] }

# USB and storage dependencies
embassy-usb = { version = "0.6.0", features = ["defmt"] }
static_cell = "2.1.1"
embedded-io-async = "0.7.0"
heapless = "0.9.3"
embassy-futures = "0.1.2"
embedded-storage = "0.3.1"
embedded-storage-async = "0.4.1"
embassy-sync = { version = "0.8.0", features = ["defmt"] }

# BLE (trouble + nrf-sdc)
nrf-sdc = { git = "https://github.com/alexmoon/nrf-sdc.git", rev = "abe49d22ebfc85fae134eb082fbfddf752016a55", default-features = false, features = ["defmt", "peripheral", "central", "nrf52840"] }
nrf-mpsl = { git = "https://github.com/alexmoon/nrf-sdc.git", rev = "abe49d22ebfc85fae134eb082fbfddf752016a55", default-features = false, features = ["defmt", "critical-section-impl", "nrf52840"] }
bt-hci = { version = "0.9", default-features = false, features = ["defmt"] }
trouble-host = { git = "https://github.com/embassy-rs/trouble", rev = "c21b1239fb86de712fc99da803def88378d81177", features = ["peripheral", "gatt", "derive", "default-packet-pool", "defmt", "security"] }

[profile.release]
codegen-units = 1
debug = 0
debug-assertions = false
incremental = false
lto = "fat"
opt-level = "z"
overflow-checks = false
panic = "abort"
strip = "symbols"

[profile.release.package.sha2]
opt-level = 3
