[workspace]

[package]
name = "pager-xiao-installer"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[dependencies]
cortex-m = { version = "0.7.9", features = ["inline-asm"] }
cortex-m-rt = "0.7.7"

[profile.release]
codegen-units = 1
debug = 0
lto = "fat"
opt-level = "s"
panic = "abort"
strip = "symbols"
