# Generated by tools/generate_protocol.py; edit protocol.json.
# fmt: off
FRAME_MAGIC = 'PGR1'
FRAME_VERSION = 5
STATE_SCHEMA = 5
MAX_PAYLOAD = 512
APPLICATION_VID = 4617
APPLICATION_PID = 2
ERRORS = {'bad_request': 1, 'unsupported_command': 2, 'busy': 3, 'dfu_failure': 4, 'hid_not_ready': 5, 'unsupported_character': 6, 'connection_lost': 7, 'queue_full': 8}
COMMANDS = {'ping': 1, 'get_info': 2, 'get_state': 3, 'activate_slot': 4, 'cancel_pairing': 5, 'set_bluetooth_enabled': 6, 'clear_slot': 7, 'type_text': 8, 'reboot_to_bootloader': 9, 'get_logs': 10, 'set_device_name': 11, 'set_slot_name': 12, 'factory_reset': 13}
HEADER_SIZE = 16
FRAME_KINDS = {'command': 1, 'response': 2, 'event': 3, 'dfu_data': 4, 'error': 5}
LIMITS = {'slots': 3, 'device_name': 24, 'slot_name': 32, 'type_text': 256}
