"""Generate the checked-in language contracts from protocol.json."""

import argparse
import json
from pathlib import Path

import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.build_ui import render_pages


def validate(spec):
    for key, maximum in [
        ("frame_version", 255),
        ("state_schema", 255),
        ("application_vid", 65535),
        ("application_pid", 65535),
        ("max_payload", 65535),
        ("header_size", 65535),
    ]:
        value = spec[key]
        if type(value) is not int or not 0 < value <= maximum:
            raise ValueError(f"invalid {key}")
    if spec["header_size"] != 16 or len(spec["frame_magic"].encode("ascii")) != 4:
        raise ValueError("unsupported frame envelope")
    for section in ("commands", "errors", "frame_kinds"):
        values = list(spec[section].values())
        if len(set(values)) != len(values) or any(
            type(v) is not int or not 0 < v <= 255 for v in values
        ):
            raise ValueError(f"invalid or duplicate {section}")
    if spec["limits"]["slots"] != 3:
        raise ValueError("storage currently requires three slots")
    for key, value in spec["limits"].items():
        if type(value) is not int or not 0 < value <= spec["max_payload"]:
            raise ValueError(f"invalid limit {key}")


def artifacts(spec):
    py = "# Generated by tools/generate_protocol.py; edit protocol.json.\n# fmt: off\n"
    for key, value in spec.items():
        py += f"{key.upper()} = {value!r}\n"
    js = "// Generated by tools/generate_protocol.py; edit protocol.json.\n"
    js += "const PAGER_PROTOCOL = Object.freeze(" + json.dumps(spec, separators=(",", ":")) + ");\n"
    result = {ROOT / "pager_tools/protocol_spec.py": py, ROOT / "web/protocol_spec.js": js}
    result.update({ROOT / name: page for name, page in render_pages(js).items()})
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    spec = json.loads((ROOT / "protocol.json").read_text())
    validate(spec)
    for path, content in artifacts(spec).items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"stale generated protocol: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)


if __name__ == "__main__":
    main()
