[workspace]

[package]
name = "pager-bootloader"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = ["dev-bootloader", "board-nice-nano-v2"]
dev-bootloader = []
release-bootloader = []
board-nice-nano-v2 = []
board-xiao-nrf52840 = []

[build-dependencies]
serde_json = "1.0.151"

[dependencies]
cortex-m = { version = "0.7.9", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.7"
ed25519-compact = { version = "2.6.0", default-features = false, features = ["opt_size"] }
sha2 = { version = "0.11.0", default-features = false }
embassy-nrf = { version = "0.11.0", path = "../vendor/embassy-nrf", features = ["nrf52840", "time-driver-rtc1", "gpiote", "unstable-pac", "rt"] }
embassy-time = { version = "0.5.1" }
embedded-storage = "0.3.2"
usb-device = "0.3.2"
nrf-usbd = "0.3.0"
usbd-storage = { path = "usbd-storage", features = ["bbb", "scsi"] }
static_cell = "2.1.1"
heapless = "0.9.3"
pager-bootloader-core = { path = "../bootloader-core" }

[profile.release]
codegen-units = 1
debug = 0
lto = "fat"
opt-level = "z"
panic = "abort"
strip = "symbols"
